// Writes the params, profile and quality reference pages from the comments
// and defaults in the library's types.ts, so the reference cannot drift from
// the code. Runs before every docs build and dev server

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

type Field = {
  key: string;
  type: string;
  value: string;
  short: string;
  paragraphs: string[];
};

type Page = {
  file: string;
  title: string;
  description: string;
  intro: string;
  type: string;
  defaults: string;
};

const types = readFileSync(
  fileURLToPath(
    new URL("../../../packages/afterburner/src/types.ts", import.meta.url),
  ),
  "utf8",
);

/**
 * Where a generated page goes.
 * @param name The page's file name, without extension
 * @returns Its path
 */
const written: string[] = [];

const page_path = (name: string): string =>
  fileURLToPath(
    new URL(`../content/docs/reference/${name}.mdx`, import.meta.url),
  );

/**
 * The body of an exported object type.
 * @param name The type's name
 * @returns What is between its braces
 */
const type_body = (name: string): string => {
  const body = types.match(
    new RegExp(`export type ${name} = \\{([\\s\\S]*?)\\n\\};`),
  )?.[1];

  if (body === undefined) throw new Error(`No type ${name} in types.ts`);

  return body;
};

/**
 * The defaults a factory returns, as source text.
 * @param name The factory's name
 * @returns Each field's default
 */
const default_values = (name: string): Record<string, string> => {
  const body = types.match(
    new RegExp(
      `export const ${name} = \\(\\): \\w+ => \\(\\{([\\s\\S]*?)\\n\\}\\);`,
    ),
  )?.[1];

  if (body === undefined) throw new Error(`No factory ${name} in types.ts`);

  return Object.fromEntries(
    [...body.matchAll(/^ {2}(\w+): (.+?),\s*$/gm)].map(([, key, value]) => [
      key,
      (value ?? "").replace(/^new Color\((".*")\)$/, "$1"),
    ]),
  );
};

/**
 * Comment lines to paragraphs.
 *
 * The source's comments leave a sentence's full stop off at a line end, so a
 * capital after an unpunctuated line starts a new sentence.
 * @param lines The comment's lines, markers stripped
 * @returns Its paragraphs
 */
const prose = (lines: string[]): string[] => {
  const paragraphs: string[][] = [[]];

  for (const line of lines) {
    const current = paragraphs[paragraphs.length - 1] ?? [];

    if (line === "") {
      if (current.length > 0) paragraphs.push([]);
      continue;
    }

    const last = current.length - 1;

    if (
      last >= 0 &&
      /^[A-Z]/.test(line) &&
      !/[.:;,]$/.test(current[last] ?? "")
    ) {
      current[last] += ".";
    }

    current.push(line);
  }

  return paragraphs
    .filter((paragraph) => paragraph.length > 0)
    .map((paragraph) => {
      const text = paragraph.join(" ");
      return /[.)]$/.test(text) ? text : `${text}.`;
    });
};

/**
 * Every field of a type, with its comment and default.
 * @param type The type's name
 * @param defaults Its defaults factory's name
 * @returns The fields, in source order
 */
const fields = (type: string, defaults: string): Field[] => {
  const values = default_values(defaults);
  const rows: Field[] = [];
  let comments: string[] = [];

  for (const raw of type_body(type).split("\n")) {
    const line = raw.trim();

    if (line.startsWith("//")) {
      comments.push(line.slice(2).trim());
    } else if (/^\w+: /.test(line)) {
      const [key = "", field_type = ""] = line
        .replace(/;$/, "")
        .split(/: (.*)/s);
      const paragraphs = prose(comments);

      rows.push({
        key,
        type: field_type,
        value: values[key] ?? "",
        short: paragraphs[0]?.split(/(?<=\.)\s/)[0] ?? "",
        paragraphs,
      });

      comments = [];
    }
  }

  return rows;
};

/**
 * Write one reference page.
 * @param page What it documents, and how it is introduced
 */
const write = ({ file, title, description, intro, type, defaults }: Page) => {
  const rows = fields(type, defaults);

  const text = [
    "---",
    `title: ${title}`,
    `description: ${JSON.stringify(description)}`,
    "---",
    "",
    "{/* Generated by scripts/reference.ts from the library's types.ts. Edit there. */}",
    "",
    intro,
    "",
    "| field | default | in short |",
    "| --- | --- | --- |",
    ...rows.map(
      ({ key, value, short }) =>
        `| [\`${key}\`](#${key}) | \`${value}\` | ${short} |`,
    ),
    "",
    ...rows.map(({ key, type: field_type, value, paragraphs }) =>
      [
        `## ${key}`,
        "",
        `\`${field_type}\` · default \`${value}\``,
        "",
        ...paragraphs.flatMap((paragraph) => [paragraph, ""]),
      ].join("\n"),
    ),
  ].join("\n");

  writeFileSync(page_path(file), text);
  written.push(page_path(file));
};

write({
  file: "params",
  title: "Params",
  description: "Every per-nozzle param, its unit, default and meaning.",
  type: "AfterburnerParams",
  defaults: "default_afterburner_params",
  intro: `Params describe **one engine**: its nozzle, the gas leaving it, and what that gas carries. They ride on the instance, so two engines in one batch may burn differently. Every one is a physical quantity in SI units.

Pass any subset as \`params\`. The rest come from the preset, then from the defaults below (\`default_afterburner_params()\`, a fighter engine at full reheat). \`params\` also takes \`propellant: { fuel, mixture_ratio }\`: see [Presets and propellants](../../guides/presets-and-propellants/#rockets-by-propellant). \`band_color\` takes any three.js \`ColorRepresentation\`.`,
});

write({
  file: "profile",
  title: "Profile",
  description:
    "Every per-batch profile field: the air, the camera and the shape constants.",
  type: "AfterburnerProfile",
  defaults: "default_afterburner_profile",
  intro: `The profile is **the world the engines run in and the camera seeing them**. It rides on the material as uniforms, shared by every nozzle in one batch, and it can change while it runs: calling \`update_profile\` every frame is fine.

Pass any subset as the batch's \`profile\`. The rest come from the batch's preset, then from these defaults (\`default_afterburner_profile()\`).`,
});

write({
  file: "quality",
  title: "Quality",
  description: "What a frame may spend on the plumes, and the quality presets.",
  type: "AfterburnerQuality",
  defaults: "default_afterburner_quality",
  intro: `Quality caps what a frame may spend. Pass \`"low"\`, \`"medium"\`, \`"high"\` or \`"ultra"\`, or any subset of the fields below. The step counts are uniforms and change live; only \`turbulence_octaves\` recompiles the material.

| preset | near_steps | mid_steps | turbulence_octaves |
| --- | --- | --- | --- |
| \`low\` | 32 | 12 | 1 |
| \`medium\` | 48 | 16 | 2 |
| \`high\` (default) | 64 | 24 | 2 |
| \`ultra\` | 112 | 40 | 3 |`,
});

// In the repo's style, so a build leaves the pages as fmt:check wants them
execSync(
  `pnpm exec oxfmt ${written.map((path) => JSON.stringify(path)).join(" ")}`,
  {
    stdio: "ignore",
  },
);
